[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Environment variables you need to set in Netlify dashboard:
# AIRTABLE_API_KEY - Your Airtable API key
# AIRTABLE_BASE_ID - Your Airtable base ID  
# OPENAI_API_KEY - Your OpenAI API key
# PORTAL_PASSWORD - Password for portal access

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200